version: "3.8"

services:
  apache:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: apache
    image: httpd:2.4
    network_mode: host
    # ports:
    #   - dock:8080
    #   - 8443:8443
    volumes:
      - ./config/my-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./config/my_vhost.conf:/usr/local/apache2/conf/my_vhost.conf:ro