version: '3.8'

services:
  master:
    image: redis:6.2.13
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./conf/kong.acl:/usr/local/etc/redis/kong.acl